"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Button } from "~/components/ui/button";
import {
	Drawer,
	DrawerClose,
	DrawerContent,
	DrawerDescription,
	DrawerFooter,
	DrawerHeader,
	DrawerTitle,
	DrawerTrigger,
} from "~/components/ui/drawer";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "~/components/ui/select";
import { Separator } from "~/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import { useIsMobile } from "~/hooks/use-mobile";
import { updateGramPanchayat } from "../actions";
import type { GramPanchayat } from "../schema";

interface GramPanchayatDetailDrawerProps {
	item: GramPanchayat;
	onUpdate?: () => void;
	trigger?: React.ReactNode;
}

export function GramPanchayatDetailDrawer({
	item,
	onUpdate,
	trigger,
}: GramPanchayatDetailDrawerProps) {
	const isMobile = useIsMobile();
	const [isSubmitting, setIsSubmitting] = useState(false);

	async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
		event.preventDefault();
		setIsSubmitting(true);

		const formData = new FormData(event.currentTarget);
		const mrfUnitId = formData.get("mrfUnitId") as string | null;
		const mrfMapped =
			mrfUnitId !== null && mrfUnitId !== "" && mrfUnitId !== "none";

		// Map MRF ID to name
		const mrfUnitMap: Record<string, string> = {
			"MRF-001": "Anjanapura MRF Unit",
			"MRF-002": "Chikkaballapura MRF Unit",
			"MRF-003": "Hosakote MRF Unit",
			"MRF-004": "Kanakapura MRF Unit",
			"MRF-005": "Nelamangala MRF Unit",
			"MRF-006": "Ramanagara MRF Unit",
			"MRF-007": "Devanahalli MRF Unit",
			"MRF-008": "Hoskote MRF Unit",
			"MRF-009": "Kolar MRF Unit",
			"MRF-010": "Chintamani MRF Unit",
		};

		const updates = {
			name: formData.get("name") as string,
			taluk: formData.get("taluk") as string,
			village: formData.get("village") as string,
			sarpanch: formData.get("sarpanch") as string,
			status: formData.get("status") as "Active" | "Inactive",
			mrfUnitId: mrfMapped && mrfUnitId ? mrfUnitId : null,
			mrfUnitName:
				mrfMapped && mrfUnitId ? (mrfUnitMap[mrfUnitId] ?? null) : null,
			mrfMapped,
			// Performance metrics are not editable - they are generated by GP
		};

		try {
			await updateGramPanchayat(item.id, updates);
			toast.success("Gram Panchayat updated successfully");
			onUpdate?.();
		} catch (error) {
			toast.error("Failed to update Gram Panchayat");
		} finally {
			setIsSubmitting(false);
		}
	}

	return (
		<Drawer direction={isMobile ? "bottom" : "right"}>
			<DrawerTrigger asChild>
				{trigger ?? (
					<Button
						variant="link"
						className="text-foreground w-fit px-0 text-left"
					>
						{item.name}
					</Button>
				)}
			</DrawerTrigger>
			<DrawerContent>
				<DrawerHeader className="gap-1">
					<DrawerTitle>{item.name}</DrawerTitle>
					<DrawerDescription>
						Manage Gram Panchayat details and performance metrics
					</DrawerDescription>
				</DrawerHeader>
				<form
					id="gram-panchayat-form"
					onSubmit={handleSubmit}
					className="flex flex-col gap-4 overflow-y-auto px-4 text-sm"
				>
					<Tabs defaultValue="basic-info" className="w-full">
						<TabsList className="grid w-full grid-cols-2">
							<TabsTrigger value="basic-info">Basic Information</TabsTrigger>
							<TabsTrigger value="performance">Performance Metrics</TabsTrigger>
						</TabsList>

						<TabsContent
							value="basic-info"
							className="flex flex-col gap-4 mt-4"
						>
							<div className="flex flex-col gap-3">
								<Label htmlFor="name">Name</Label>
								<Input
									id="name"
									name="name"
									defaultValue={item.name}
									required
								/>
							</div>

							<div className="grid grid-cols-2 gap-4">
								<div className="flex flex-col gap-3">
									<Label htmlFor="taluk">Taluk</Label>
									<Input
										id="taluk"
										name="taluk"
										defaultValue={item.taluk}
										required
									/>
								</div>
								<div className="flex flex-col gap-3">
									<Label htmlFor="village">Village</Label>
									<Input
										id="village"
										name="village"
										defaultValue={item.village}
										required
									/>
								</div>
							</div>

							<div className="grid grid-cols-2 gap-4">
								<div className="flex flex-col gap-3">
									<Label htmlFor="sarpanch">Sarpanch</Label>
									<Input
										id="sarpanch"
										name="sarpanch"
										defaultValue={item.sarpanch}
										required
									/>
								</div>
								<div className="flex flex-col gap-3">
									<Label htmlFor="status">Status</Label>
									<Select name="status" defaultValue={item.status}>
										<SelectTrigger id="status" className="w-full">
											<SelectValue placeholder="Select status" />
										</SelectTrigger>
										<SelectContent>
											<SelectItem value="Active">Active</SelectItem>
											<SelectItem value="Inactive">Inactive</SelectItem>
										</SelectContent>
									</Select>
								</div>
							</div>

							<Separator />

							<div className="flex flex-col gap-3">
								<Label htmlFor="mrfUnitId">MRF Unit</Label>
								<Select
									name="mrfUnitId"
									defaultValue={item.mrfUnitId ?? "none"}
								>
									<SelectTrigger id="mrfUnitId" className="w-full">
										<SelectValue placeholder="Select MRF Unit" />
									</SelectTrigger>
									<SelectContent>
										<SelectItem value="none">Not Mapped</SelectItem>
										<SelectItem value="MRF-001">
											MRF-001 - Anjanapura MRF Unit
										</SelectItem>
										<SelectItem value="MRF-002">
											MRF-002 - Chikkaballapura MRF Unit
										</SelectItem>
										<SelectItem value="MRF-003">
											MRF-003 - Hosakote MRF Unit
										</SelectItem>
										<SelectItem value="MRF-004">
											MRF-004 - Kanakapura MRF Unit
										</SelectItem>
										<SelectItem value="MRF-005">
											MRF-005 - Nelamangala MRF Unit
										</SelectItem>
										<SelectItem value="MRF-006">
											MRF-006 - Ramanagara MRF Unit
										</SelectItem>
										<SelectItem value="MRF-007">
											MRF-007 - Devanahalli MRF Unit
										</SelectItem>
										<SelectItem value="MRF-008">
											MRF-008 - Hoskote MRF Unit
										</SelectItem>
										<SelectItem value="MRF-009">
											MRF-009 - Kolar MRF Unit
										</SelectItem>
										<SelectItem value="MRF-010">
											MRF-010 - Chintamani MRF Unit
										</SelectItem>
									</SelectContent>
								</Select>
							</div>

							<div className="flex flex-col gap-3">
								<Label htmlFor="dateCreated">Date Created</Label>
								<Input
									id="dateCreated"
									type="date"
									defaultValue={item.dateCreated}
									disabled
									className="bg-muted"
								/>
							</div>
						</TabsContent>

						<TabsContent
							value="performance"
							className="flex flex-col gap-4 mt-4"
						>
							<div className="text-muted-foreground mb-2 text-sm">
								Performance metrics are generated by the Gram Panchayat and are
								read-only.
							</div>
							<div className="grid grid-cols-2 gap-4">
								<div className="flex flex-col gap-3">
									<Label htmlFor="households">Households</Label>
									<Input
										id="households"
										name="households"
										type="number"
										defaultValue={item.households}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
								<div className="flex flex-col gap-3">
									<Label htmlFor="shops">Shops</Label>
									<Input
										id="shops"
										name="shops"
										type="number"
										defaultValue={item.shops}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
							</div>

							<div className="grid grid-cols-2 gap-4">
								<div className="flex flex-col gap-3">
									<Label htmlFor="institutions">Institutions</Label>
									<Input
										id="institutions"
										name="institutions"
										type="number"
										defaultValue={item.institutions}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
								<div className="flex flex-col gap-3">
									<Label htmlFor="swmSheds">SWM Sheds</Label>
									<Input
										id="swmSheds"
										name="swmSheds"
										type="number"
										defaultValue={item.swmSheds}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
							</div>

							<Separator />

							<div className="grid grid-cols-3 gap-4">
								<div className="flex flex-col gap-3">
									<Label htmlFor="wetWaste">Wet Waste (kg)</Label>
									<Input
										id="wetWaste"
										name="wetWaste"
										type="number"
										defaultValue={item.wetWaste}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
								<div className="flex flex-col gap-3">
									<Label htmlFor="dryWaste">Dry Waste (kg)</Label>
									<Input
										id="dryWaste"
										name="dryWaste"
										type="number"
										defaultValue={item.dryWaste}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
								<div className="flex flex-col gap-3">
									<Label htmlFor="sanitaryWaste">Sanitary Waste (kg)</Label>
									<Input
										id="sanitaryWaste"
										name="sanitaryWaste"
										type="number"
										defaultValue={item.sanitaryWaste}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
							</div>

							<Separator />

							<div className="grid grid-cols-2 gap-4">
								<div className="flex flex-col gap-3">
									<Label htmlFor="revenue">Revenue (₹)</Label>
									<Input
										id="revenue"
										name="revenue"
										type="number"
										defaultValue={item.revenue}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
								<div className="flex flex-col gap-3">
									<Label htmlFor="complianceScore">Compliance Score (%)</Label>
									<Input
										id="complianceScore"
										name="complianceScore"
										type="number"
										min="0"
										max="100"
										defaultValue={item.complianceScore}
										disabled
										className="bg-muted"
										readOnly
									/>
								</div>
							</div>

							<div className="flex flex-col gap-3">
								<Label htmlFor="lastUpdated">Last Updated</Label>
								<Input
									id="lastUpdated"
									type="date"
									defaultValue={item.lastUpdated}
									disabled
									className="bg-muted"
								/>
							</div>
						</TabsContent>
					</Tabs>
				</form>
				<DrawerFooter>
					<Button
						type="submit"
						form="gram-panchayat-form"
						disabled={isSubmitting}
					>
						{isSubmitting ? "Saving..." : "Submit"}
					</Button>
					<DrawerClose asChild>
						<Button variant="outline">Cancel</Button>
					</DrawerClose>
				</DrawerFooter>
			</DrawerContent>
		</Drawer>
	);
}
